name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_barcode_scanner: ^0.0.8
  sqflite: ^2.3.2
  path: 1.8.3
  sqflite_common_ffi: 2.3.2+1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
      - asset/images/

  

  