name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_barcode_scanner: ^0.1.0
  
  path_provider: any
  
  path: 1.9.0
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^0.8.4+2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
      - asset/images/
      

  

  